---
- name: Install vim standard setup
  include: vim_standard_setup.yml username="{{ item }}"
  tags: vim

- name: Install zsh standard setup
  include: zsh_standard_setup.yml username="{{ item }}"
  tags: zsh

- name: Install git standard setup
  include: git_standard_setup.yml username="{{ item }}"
  tags: git
